### ISSUE TITLE
KeyError in SORTER2_Stage2_PhaseOrthologs.py

### ISSUE THREAD

**Issue by kroeve** [JonasMendez/SORTER2#1]
Hi @JonasMendez !

I'm trying to set up SORTER2 and encounter an issue when executing the script `SORTER2_Stage2_PhaseOrthologs.py`. The script exits with following error:

```
Traceback (most recent call last):
  File "SORTER2_Stage2_PhaseOrthologs.py", line 603, in <module>
    writer.writerow([ind]+[HETDICT[ind][stat] for stat in stats])
  File "SORTER2_Stage2_PhaseOrthologs.py", line 603, in <listcomp>
    writer.writerow([ind]+[HETDICT[ind][stat] for stat in stats])
KeyError: 'in'
```

Do you have any idea what might cause the problem? I installed all dependencies listed and mostly used the recommended version, although due to some compatibility issues in conda I sometimes had to install different versions. Please let me know if you need further information for solving this issue!

Cheers,
Evelin

**Comment by JonasMendez** [comment]
Seems like this issue was an oversight on my part in how samtools outputs bam read statistics between v1.10 and v1.21; I have updated the scripts and documentation to require samtools v1.21. There may be additional issues, so I will leave the issue open for the time being until I confirm this has resolved the error. Feel free to post here if you are having the same problem with samtools v1.21, Thank you
